[colors.bright]
black = "0x888888"
blue = "0x289cd5"
cyan = "0x0a9b81"
green = "0x76b639"
magenta = "0xff2491"
red = "0xff0000"
white = "0xf8f8f8"
yellow = "0xe1a126"

[colors.normal]
black = "0x171717"
blue = "0x16b1fb"
cyan = "0x0fdcb6"
green = "0x97d01a"
magenta = "0xff2491"
red = "0xd81765"
white = "0xebebeb"
yellow = "0xffa800"

[colors.primary]
background = "0x171717"
foreground = "0xf8f8f8"

[window]
opacity=0.8

[font]
size = 12

[font.bold]
family = "0xproto"
style = "Bold"

[font.bold_italic]
family = "0xproto"
style = "Bold Italic"

[font.italic]
family = "0xproto"
style = "Italic"

[font.normal]
family = "0xproto"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = 374

[window.dimensions]
columns = 114
lines = 30


